### ISSUE TITLE
Issue when getting depedencies

### ISSUE THREAD

**Issue by MyUsernamee** [sc2ad/QuestPackageManager#27]
When I try to run `qpm restore` I get this error.

``` Creating config at: C:\Program Files\QPM\appsettings.json
Configuration could not be loaded!
Creating new local config at: C:\Users\Delano Leslie\Desktop\Gorilla\qpm.shared.json
Created symlink from C:\Users\Delano Leslie\AppData\Local\QPM_Temp\beatsaber-hook\3.3.3\libs\libbeatsaber-hook_3_3_3.so to C:\Users\Delano Leslie\Desktop\Gorilla\extern\libbeatsaber-hook_3_3_3.so
Created symlink from C:\Users\Delano Leslie\AppData\Local\QPM_Temp\modloader\1.2.3\libs\libmodloader.so to C:\Users\Delano Leslie\Desktop\Gorilla\extern\libmodloader.so
Trying to clone from: https://github.com/sc2ad/beatsaber-hook.git to: C:\Users\Delano Leslie\AppData\Local\QPM_Temp\beatsaber-hook\3.3.3\src
Could not find a part of the path 'C:\Users\Delano Leslie\AppData\Local\QPM_Temp\beatsaber-hook\3.3.3\src'.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Delano Leslie\AppData\Local\QPM_Temp\beatsaber-hook\3.3.3\src'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path)
   at QPM.Utils.GetSubdir(String path) in D:\a\QuestPackageManager\QuestPackageManager\QPM\Utils.cs:line 236
   at QPM.RemoteQPMDependencyResolver.ResolveUniqueDependency(Config myConfig, KeyValuePair`2 resolved) in D:\a\QuestPackageManager\QuestPackageManager\QPM\Providers\RemoteQPMDependencyResolver.cs:line 568   
   at QuestPackageManager.RestoreHandler.Restore() in D:\a\QuestPackageManager\QuestPackageManager\QuestPackageManager\Handlers\RestoreHandler.cs:line 237
   at QPM.Commands.RestoreCommand.OnExecute() in D:\a\QuestPackageManager\QuestPackageManager\QPM\Commands\RestoreCommand.cs:line 63
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at QPM.Program.Main(String[] args) in D:\a\QuestPackageManager\QuestPackageManager\QPM\Program.cs:line 134
Failed! ```


Checking the directory there is only a libs folder. When I manually get the git it works fine, I can get the src folder, but when i run restore it overrides it and throws this error.

**Comment by sc2ad** [comment]
Please update your QPM to latest and reopen this issue if this still happens.
